name: tests

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: "AB"
        description: "ola2"

  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"
  job2:
    concurrency:
      group: ${{ github.workflow }}-${{ github.run_id }}-${{ github.run_attempt	}}-tests
    needs:
      - job1
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"

  job3:
    concurrency:
      group: ${{ github.workflow }}-${{ github.run_id }}-${{ github.run_attempt	}}-tests
    needs:
      - job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"

  job4:
    concurrency:
      group: ${{ github.workflow }}-${{ github.run_id }}-${{ github.run_attempt	}}-tests
    needs:
      - job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"
