name: tests

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: "ola"
        description: "ola2"

  schedule:
    - "*/5 * * * *"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}
