name: tests

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: "${{ vars.AB }}"
        description: "ola2"

  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"
  job2:
    needs:
      - job1
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"

  job3:
    needs:
      - job2
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.tests }}"
